old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
            port: 5672
            user: '%env(RABBITMQ_USER)%'
            password: '%env(RABBITMQ_PASSWORD)%'
            vhost: '/'
            lazy: false
    producers:
        product_export:
            connection: default
            exchange_options:
                name: 'products_exchange'
                type: direct
            default_routing_key: 'product_key'
    consumers:
        product_import:
            connection: default
            exchange_options:
                name: 'products_exchange'
                type: direct
            queue_options:
                name: 'products_queue'
                routing_keys:
                    - 'product_key'
            callback: 'App\Consumer\ProductImportConsumer'
